ALTER TABLE scans ADD COLUMN files_total INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scans ADD COLUMN files_completed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE scans ADD COLUMN coverage_json TEXT;
ALTER TABLE scans ADD COLUMN capability_json TEXT;
